apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      volumes:
        - name: tls-cert
          secret:
            secretName: wisecow-tls-secret
        - name: nginx-config
          configMap:
            name: nginx-config
      containers:
      - name: wisecow
        image: shefeekar/wisecow:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4499
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 443
        volumeMounts:
            - name: tls-cert
              mountPath: /etc/nginx/ssl
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf 
