
apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: NodePort
  ports:
    - protocol: TCP
      port: 4499
      targetPort: 4499
      nodePort: 30499
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-wisecow-service
spec:
  selector:
    app: wisecow
  type: NodePort
  ports:
    - name: https
      port: 443           
      targetPort: 443 
      nodePort: 30443 
      protocol: TCP     